# -*- mode: python -*-
# 

import frogsutils

def build( bld ):
    sources = bld.path.ant_glob('*.F')    
    lib = bld(features='fc fcshlib',
              target = 'poloka-cern', 
              source = sources,
              includes = ['.', '..'], 
              libs     = ['m'], 
              vnum     = frogsutils.get_version_number())
    #    lib.rpath = [bld.env.PREFIX + '/lib']
    #    headers = bld.path.ant_glob('*.h')
    #    bld.install_files('${PREFIX}/${PKG_INCDIR}', headers)
